version: '3.3'

services:

      
        
  # ===================
  #    java BACKEND 
  # ===================

  big-data-training-scala-kafka-backend:
    image: big-data-training-java-kafka-backend
    build:
      context: ../../src/backend/scala
      dockerfile: ./Dockerfile
    ports:
      - "8089:8088"
    networks:
      - big-data-training-java-kafka

networks:
  big-data-training-java-kafka:
    driver: bridge
  